server:
  port: 8050
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuanmenghaixin/spring-cloud-study/
          search-paths: 2016-Brixton/config-repo
          username: 710584845@qq.com
          password:

#management:                    #SpringCloud 1.5版本暴露接口，暴露/bus-refresh接口
#  security:
#    enabled: false
#  endpoints:                  #SpringCloud 2.0.0版本以后暴露接口方式
#    web:
#      exposure:
#        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/