server:
  port: 8761
eureka:
  instance:
    hostname: eurekaServer
    prefer-ip-address: true #将自己的IP注册到eureka server
  client:
    # 是否要注册到其他Eureka Server实例
    registerWithEureka: false
    # 是否要从其他Eureka Server 实例获取数据
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
